# -*- coding: utf-8 -*-
"""MK 6 W3: Business Analytics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16fRQbwYLuXjx9oWgt4X0SQ8EJa5B2g2h
"""

import pandas as pd

dt_store = pd.read_excel('/content/Global_Superstore2.xlsx')
dt_store.head(15)

dt_store.info()

dt_store.duplicated().sum()

features = [
    "Ship Mode",
    "Segment",
    # "City",
    # "State",
    "Country",
    "Market",
    "Region",
    "Category",
    "Sub-Category",
    # "Product Name",
    "Order Priority"
]

total_rows = len(dt_store)

for feature in features:
    print("=" * 60)
    print(f"VALUE COUNTS: {feature}")
    print("=" * 60)
    print(f"{'Value':<30} {'Count':<10} {'Percentage'}")
    print("-" * 60)

    counts = dt_store[feature].value_counts(dropna=False)

    for value, count in counts.items():
        pct = (count / total_rows) * 100
        print(f"{str(value):<30} {count:<10} {pct:.2f}%")

    print()

# unique values all features

unique = [
    "Ship Mode",
    "Segment",
    "City",
    "State",
    "Country",
    "Market",
    "Region",
    "Category",
    "Sub-Category",
    "Product Name",
    "Order Priority"
]

for feature in unique:
    print("=" * 60)
    print(f"TOTAL UNIQUE VALUES: {feature}")
    print("=" * 60)

    # dropna=False memastikan missing value (NaN) tetap dihitung sebagai salah satu nilai unik
    n_unique = dt_store[feature].nunique(dropna=False)
    print(f"Banyak nilai unik: {n_unique}")
    print()

"""# Task 1 — Is Global Superstore Really Underperforming?
1. Analyse overall Sales, Profit, and Profit Margin (Profit ÷ Sales) for each year from 2011 to 2014.
2. Calculate year-on-year growth and look at monthly or quarterly trends.

Answer:
* Are sales and profit growing, flat, or declining? Is the profit margin improving or worsening?
* Is the company underperforming overall, or only in certain areas? Justify your answer with data.
"""

# Ekstrak tahun
dt_store['Order Date'] = pd.to_datetime(dt_store['Order Date'], format='%d-%m-%Y')
dt_store['Year'] = dt_store['Order Date'].dt.year

# Filter tahun 2011-2014 dan agregasi
yearly_summary = (
    dt_store[dt_store['Year'].between(2011, 2014)]
    .groupby('Year')
    .agg(
        Total_Sales=('Sales', 'sum'),
        Total_Profit=('Profit', 'sum')
    )
    .reset_index()
)

# Hitung Profit Margin
yearly_summary['Profit Margin'] = yearly_summary['Total_Profit'] / yearly_summary['Total_Sales']
yearly_summary['Profit Margin Pct'] = (yearly_summary['Profit Margin'] * 100).round(2).astype(str) + '%'

yearly_summary

# Buat visualisasi

import matplotlib.pyplot as plt
import seaborn as sns

viz = [
    'Total_Sales',
    'Total_Profit',
    'Profit Margin'
]

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

for idx, metric in enumerate(viz):
    ax = axes[idx]
    sns.barplot(data=yearly_summary, x='Year', y=metric, ax=ax, hue='Year', palette='crest', legend=False)

    clean_title = metric.replace('_', ' ').title()
    ax.set_title(clean_title, fontsize=12, fontweight='bold')
    ax.set_xlabel('Year')
    ax.set_ylabel('')

    for p in ax.patches:
        val = p.get_height()
        label = f"{val * 100:.2f}%" if 'Margin' in metric else f"{val:,.0f}"
        ax.annotate(
            label,
            (p.get_x() + p.get_width() / 2., val),
            ha='center', va='bottom' if val >= 0 else 'top',
            fontsize=9, fontweight='bold',
            xytext=(0, 4 if val >= 0 else -12),
            textcoords='offset points'
        )

plt.tight_layout()
plt.show()

import numpy as np

# 1. Pastikan kolom datetime dan filter 2011-2014
dt_store['Order Date'] = pd.to_datetime(dt_store['Order Date'])
dt_store['Year'] = dt_store['Order Date'].dt.year

df_filtered = dt_store[dt_store['Year'].between(2011, 2014)].copy()

# 2. Agregasi tahunan
yearly = (
    df_filtered.groupby('Year')
    .agg(
        Total_Sales=('Sales', 'sum'),
        Total_Profit=('Profit', 'sum')
    )
    .reset_index()
)

# 3. Hitung Profit Margin & Pertumbuhan YoY (%)
yearly['Profit_Margin'] = yearly['Total_Profit'] / yearly['Total_Sales']
yearly['Sales_YoY_Growth'] = yearly['Total_Sales'].pct_change() * 100
yearly['Profit_YoY_Growth'] = yearly['Total_Profit'].pct_change() * 100

# Format tampilan tabel
YoY_growth_df = yearly.copy()
YoY_growth_df['Sales_YoY_Growth'] = YoY_growth_df['Sales_YoY_Growth'].apply(lambda x: f"{x:+.2f}%" if pd.notnull(x) else "-")
YoY_growth_df['Profit_YoY_Growth'] = YoY_growth_df['Profit_YoY_Growth'].apply(lambda x: f"{x:+.2f}%" if pd.notnull(x) else "-")
YoY_growth_df['Profit_Margin'] = (YoY_growth_df['Profit_Margin'] * 100).round(2).astype(str) + '%'

print("=== RINGKASAN PERFORMA & YOY GROWTH (2011 - 2014) ===")
print(YoY_growth_df.to_string(index=False))

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Hitung YoY Growth dalam bentuk ANGKA FLOAT murni (JANGAN diformat teks/string dahulu)
yoy_df = yearly_summary.copy()

yoy_df['Sales_YoY_Growth'] = yoy_df['Total_Sales'].pct_change() * 100
yoy_df['Profit_YoY_Growth'] = yoy_df['Total_Profit'].pct_change() * 100
yoy_df['Profit_Margin'] = (yoy_df['Total_Profit'] / yoy_df['Total_Sales']) * 100

# 2. Buang baris 2011 yang bernilai NaN agar tidak muncul '2010-2011'
yoy_df = yoy_df.dropna(subset=['Sales_YoY_Growth']).copy()

# 3. Buat label rentang periode untuk sumbu X (hanya 2011-2012, 2012-2013, 2013-2014)
yoy_df['Period'] = [f"{int(y)-1}-{int(y)}" for y in yoy_df['Year']]

# 4. Visualisasi Barplot
viz = [
    'Sales_YoY_Growth',
    'Profit_YoY_Growth',
    'Profit_Margin'
]

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
sns.set_theme(style="whitegrid")

for idx, metric in enumerate(viz):
    ax = axes[idx]

    # Plot bar dengan nilai numerik riil
    sns.barplot(
        data=yoy_df,
        x='Period',
        y=metric,
        ax=ax,
        hue='Period',
        palette='crest',
        legend=False
    )

    clean_title = metric.replace('_', ' ').title()
    ax.set_title(f"{clean_title} (%)", fontsize=12, fontweight='bold', pad=10)
    ax.set_xlabel('Period', fontsize=10)
    ax.set_ylabel('Percentage (%)', fontsize=10)

    # Garis horizontal nol
    ax.axhline(0, color='black', linewidth=0.8, linestyle='--')

    # Label angka di atas batang
    for p in ax.patches:
        val = p.get_height()
        label = f"{val:+.2f}%" if 'Growth' in metric else f"{val:.2f}%"

        va_align = 'bottom' if val >= 0 else 'top'
        y_offset = 4 if val >= 0 else -12

        ax.annotate(
            label,
            (p.get_x() + p.get_width() / 2., val),
            ha='center', va=va_align,
            fontsize=10, fontweight='bold',
            xytext=(0, y_offset),
            textcoords='offset points'
        )

    y_min, y_max = ax.get_ylim()
    ax.set_ylim(min(0, y_min * 1.2), max(0, y_max * 1.25))

plt.tight_layout()
plt.show()

# Ekstrak kuartal
df_filtered['Quarter'] = 'Q' + df_filtered['Order Date'].dt.quarter.astype(str)

quarterly_summary = (
    df_filtered.groupby(['Year', 'Quarter'])
    .agg(
        Total_Sales=('Sales', 'sum'),
        Total_Profit=('Profit', 'sum')
    )
    .reset_index()
)

quarterly_summary['Profit_Margin'] = quarterly_summary['Total_Profit'] / quarterly_summary['Total_Sales']

# Sort by Year and Quarter for correct sequential percentage change calculation
quarterly_summary = quarterly_summary.sort_values(by=['Year', 'Quarter']).reset_index(drop=True)

# Calculate sequential Quarter-on-Quarter Growth
quarterly_summary['Growth_per_month'] = quarterly_summary['Total_Sales'].pct_change() * 100
quarterly_summary['Growth_per_month'] = quarterly_summary['Growth_per_month'].apply(lambda x: f"{x:+.2f}%" if pd.notna(x) else "-")
print(quarterly_summary.head())

import matplotlib.pyplot as plt
import seaborn as sns

metrics_to_plot = [
    'Total_Sales',
    'Total_Profit',
    'Profit_Margin'
]

years = quarterly_summary['Year'].unique()

for year in years:
    yearly_quarterly_data = quarterly_summary[quarterly_summary['Year'] == year]

    fig, axes = plt.subplots(1, 3, figsize=(20, 6))
    fig.suptitle(f'Quarterly Performance for Year {year}', fontsize=16, fontweight='bold', y=1.02)

    for idx, metric in enumerate(metrics_to_plot):
        ax = axes[idx]
        sns.barplot(data=yearly_quarterly_data, x='Quarter', y=metric, ax=ax, palette='viridis', hue='Quarter', legend=False)

        clean_title = metric.replace('_', ' ').title()
        ax.set_title(clean_title, fontsize=12, fontweight='bold')
        ax.set_xlabel('Quarter', fontsize=10)
        ax.set_ylabel(metric.replace('_', ' ').title(), fontsize=10)

        for p in ax.patches:
            val = p.get_height()
            if 'Margin' in metric:
                label = f"{val * 100:.2f}%"
            else:
                label = f"{val:,.0f}"
            ax.annotate(
                label,
                (p.get_x() + p.get_width() / 2., val),
                ha='center', va='bottom' if val >= 0 else 'top',
                fontsize=8, fontweight='bold',
                xytext=(0, 4 if val >= 0 else -12),
                textcoords='offset points'
            )

    plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to prevent suptitle overlap
    plt.show()

"""# Task 2 — Find Where the Problem Is
1. Drill down by geography: Market → Region → Country.
2. Drill down by product: Category → Sub-Category → Product.
3. Compare customer Segments, and combine dimensions to find specific trouble spots.

Answer:
* Which markets, regions, and countries have low or declining profit and margin?
* Which categories and sub-categories lose money? Is it a volume problem or a margin problem?
* Where exactly are the biggest losses concentrated?
"""

# Pastikan tipe data datetime sudah siap
dt_store['Order Date'] = pd.to_datetime(dt_store['Order Date'])
dt_store['Year'] = dt_store['Order Date'].dt.year

def calculate_kpi(df, group_cols):
    """Menghitung ringkasan metrik finansial teragregasi."""
    summary = (
        df.groupby(group_cols)
        .agg(
            Total_Sales=('Sales', 'sum'),
            Total_Profit=('Profit', 'sum'),
            Total_Qty=('Quantity', 'sum'),
            Avg_Discount=('Discount', 'mean'),
            Order_Count=('Order ID', 'nunique') if 'Order ID' in df.columns else ('Sales', 'count')
        )
        .reset_index()
    )
    summary['Profit_Margin_%'] = (summary['Total_Profit'] / summary['Total_Sales']) * 100
    summary['Avg_Discount_%'] = summary['Avg_Discount'] * 100
    return summary

# A. Level Market
geo_market = calculate_kpi(dt_store, ['Market']).sort_values('Profit_Margin_%')
print("=== PERFORMA FINANSIAL PER MARKET ===")
print(geo_market[['Market', 'Total_Sales', 'Total_Profit', 'Profit_Margin_%', 'Avg_Discount_%']].to_string(index=False))
print("\n")

# B. Level Region (Identifikasi Region dengan Profit Terendah / Negatif)
geo_region = calculate_kpi(dt_store, ['Market', 'Region']).sort_values('Total_Profit')
print("=== TOP 5 REGION PALING BERMASALAH (PROFIT TERENDAH) ===")
print(geo_region.head(5)[['Market', 'Region', 'Total_Sales', 'Total_Profit', 'Profit_Margin_%', 'Avg_Discount_%']].to_string(index=False))
print("\n")

# C. Level Country (Daftar Negara yang Mengalami Kerugian Total)
geo_country = calculate_kpi(dt_store, ['Market', 'Region', 'Country']).sort_values('Total_Profit')
loss_countries = geo_country[geo_country['Total_Profit'] < 0]

print(f"=== DAFTAR NEGARA DENGAN PROFIT MINUS ({len(loss_countries)} NEGARA) ===")
print(loss_countries.head(10)[['Country', 'Market', 'Region', 'Total_Sales', 'Total_Profit', 'Profit_Margin_%', 'Avg_Discount_%']].to_string(index=False))
print("\n")

# D. Analisis Tren Profit Menurun per Tahun (Declining Profit Check)
market_trend = (
    dt_store.groupby(['Market', 'Year'])['Profit']
    .sum()
    .unstack()
    .fillna(0)
)
market_trend['YoY_Change_2013_2014'] = market_trend[2014] - market_trend[2013]
print("=== TREN PERTUMBUHAN PROFIT MARKET PER TAHUN ===")
print(market_trend)

# A. Agregasi Sub-Category
product_subcat = calculate_kpi(dt_store, ['Category', 'Sub-Category']).sort_values('Total_Profit')

# B. Klasifikasi Masalah (Volume Problem vs Margin Problem)
# Logika Diagnostik:
# - Margin Problem: Sales tinggi / Qty banyak, tetapi Margin negatif (biasanya karena diskon terlalu boros).
# - Volume Problem: Margin positif / wajar, tetapi Sales dan Qty sangat kecil sehingga nominal profit tidak tumbuh.
def diagnose_problem(row, median_sales):
    if row['Total_Profit'] < 0:
        if row['Total_Sales'] >= median_sales:
            return "Severe Margin Problem (High Sales, Deep Loss)"
        else:
            return "Margin Problem (Loss despite low sales)"
    else:
        if row['Total_Sales'] < median_sales and row['Profit_Margin_%'] > 10:
            return "Volume Problem (Good Margin, Low Sales Volume)"
        return "Healthy / Profitable"

median_sales = product_subcat['Total_Sales'].median()
product_subcat['Diagnosis'] = product_subcat.apply(diagnose_problem, median_sales=median_sales, axis=1)

print("=== ANALISIS SUB-CATEGORY (PROFIT & DIAGNOSIS) ===")
print(product_subcat[['Category', 'Sub-Category', 'Total_Sales', 'Total_Qty', 'Total_Profit', 'Profit_Margin_%', 'Avg_Discount_%', 'Diagnosis']].to_string(index=False))

# 1. Filter baris: ambil semua data KECUALI 'Healthy / Profitable'
problematic_subcat = product_subcat[product_subcat['Diagnosis'] != 'Healthy / Profitable'].copy()

# 2. Urutkan dari profit terendah / paling rugi
problematic_subcat = problematic_subcat.sort_values('Total_Profit')

# 3. Kolom yang ingin ditampilkan
cols_to_show = [
    'Category',
    'Sub-Category',
    'Total_Sales',
    'Total_Qty',
    'Total_Profit',
    'Profit_Margin_%',
    'Avg_Discount_%',
    'Diagnosis'
]

print("=== DAFTAR SUB-CATEGORY BERMASALAH (3 KATEGORI MASALAH) ===")
print(problematic_subcat[cols_to_show].to_string(index=False))
print("\n")

# 4. Ringkasan jumlah sub-kategori di tiap kategori masalah
print("=== JUMLAH SUB-CATEGORY PER JENIS MASALAH ===")
print(problematic_subcat['Diagnosis'].value_counts().to_string())

# A. Performa per Customer Segment
segment_summary = calculate_kpi(dt_store, ['Segment']).sort_values('Total_Profit', ascending=False)
print("=== PERFORMA PROFIT PER SEGMENT ===")
print(segment_summary[['Segment', 'Total_Sales', 'Total_Profit', 'Profit_Margin_%', 'Avg_Discount_%']].to_string(index=False))
print("\n")

# B. Irisan Dimensi: Kombinasi Country + Sub-Category dengan Kerugian Terbesar
trouble_spots = calculate_kpi(dt_store, ['Country', 'Category', 'Sub-Category']).sort_values('Total_Profit')

print("=== TOP 10 TITIK KERUGIAN TERBESAR (SPECIFIC TROUBLE SPOTS) ===")
print(
    trouble_spots.head(10)[
        ['Country', 'Sub-Category', 'Total_Sales', 'Total_Profit', 'Profit_Margin_%', 'Avg_Discount_%']
    ].to_string(index=False)
)

fig, axes = plt.subplots(2, 2, figsize=(18, 11))
sns.set_theme(style="whitegrid")

# 1. 10 Negara dengan Rugi Terbesar
top_loss_countries = loss_countries.head(10).sort_values('Total_Profit', ascending=True)
sns.barplot(data=top_loss_countries, y='Country', x='Total_Profit', ax=axes[0, 0], palette='Reds_r')
axes[0, 0].set_title('Top 10 Loss-Making Countries', fontsize=12, fontweight='bold')
axes[0, 0].set_xlabel('Total Profit ($)')

# 2. Profit per Sub-Category
palette_subcat = ['red' if x < 0 else 'steelblue' for x in product_subcat['Total_Profit']]
sns.barplot(data=product_subcat, y='Sub-Category', x='Total_Profit', ax=axes[0, 1], palette=palette_subcat)
axes[0, 1].set_title('Profit by Sub-Category (Red = Losing Money)', fontsize=12, fontweight='bold')
axes[0, 1].axvline(0, color='black', linestyle='--', linewidth=0.8)
axes[0, 1].set_xlabel('Total Profit ($)')

# 3. Scatter Plot Diagnosis: Discount vs Profit Margin per Transaksi/Sub-Kategori
sns.scatterplot(
    data=product_subcat,
    x='Avg_Discount_%',
    y='Profit_Margin_%',
    size='Total_Sales',
    hue='Category',
    sizes=(50, 400),
    ax=axes[1, 0]
)
axes[1, 0].axhline(0, color='red', linestyle='--', linewidth=0.9)
axes[1, 0].set_title('Diagnosis: Avg Discount vs Profit Margin by Sub-Category', fontsize=12, fontweight='bold')
axes[1, 0].set_ylabel('Profit Margin (%)')
axes[1, 0].set_xlabel('Average Discount (%)')

# 4. Heatmap Konsentrasi Kerugian: Sub-Category pada Top 5 Negara Paling Rugi
top5_loss_country_names = top_loss_countries['Country'].head(5).tolist()
df_pivot = dt_store[dt_store['Country'].isin(top5_loss_country_names)].pivot_table(
    index='Sub-Category',
    columns='Country',
    values='Profit',
    aggfunc='sum',
    fill_value=0
)
sns.heatmap(df_pivot, cmap='RdBu', center=0, annot=True, fmt=',.0f', ax=axes[1, 1], cbar=False)
axes[1, 1].set_title('Concentration of Losses (Top 5 Loss Countries vs Sub-Category)', fontsize=12, fontweight='bold')

plt.tight_layout()
plt.show()

"""# Task 3 — Find Out Why It Happens
1. Investigate the factors behind the problem areas, such as Discount, Shipping Cost, Ship Mode,
Order Priority, and product mix.
2. Keep asking “why?” until you reach a cause the company can act on.

Answer:
* How does the discount level affect profit? Is there a level at which orders become unprofitable?
* Do shipping costs erode profit in particular markets?
* What are the 3–5 root causes of the underperformance?
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Buat Bins Diskon
discount_bins = [-0.01, 0.0, 0.10, 0.20, 0.30, 0.40, 0.50, 1.0]
discount_labels = ['0%', '1% - 10%', '11% - 20%', '21% - 30%', '31% - 40%', '41% - 50%', '> 50%']

dt_store['Discount_Band'] = pd.cut(dt_store['Discount'], bins=discount_bins, labels=discount_labels)

# Agregasi Metrik berdasarkan Tingkat Diskon
discount_analysis = dt_store.groupby('Discount_Band', observed=False).agg(
    Order_Count=('Sales', 'count'),
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Profit', 'sum'),
    Avg_Profit=('Profit', 'mean'),
    Total_Loss_Orders=('Profit', lambda x: (x < 0).sum())
).reset_index()

discount_analysis['Profit_Margin_%'] = (discount_analysis['Total_Profit'] / discount_analysis['Total_Sales']) * 100
discount_analysis['Loss_Rate_%'] = (discount_analysis['Total_Loss_Orders'] / discount_analysis['Order_Count']) * 100

print("=== PENGARUH TINGKAT DISKON TERHADAP PROFITABILITAS ===")
print(discount_analysis[['Discount_Band', 'Order_Count', 'Total_Sales', 'Total_Profit', 'Profit_Margin_%', 'Loss_Rate_%']].to_string(index=False))

# Rasio Shipping Cost terhadap Sales per Market
market_shipping = dt_store.groupby('Market').agg(
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Profit', 'sum'),
    Total_Shipping_Cost=('Shipping Cost', 'sum'),
    Avg_Shipping_Cost=('Shipping Cost', 'mean')
).reset_index()

market_shipping['Shipping_to_Sales_%'] = (market_shipping['Total_Shipping_Cost'] / market_shipping['Total_Sales']) * 100
market_shipping['Profit_Margin_%'] = (market_shipping['Total_Profit'] / market_shipping['Total_Sales']) * 100

print("=== EFISIENSI ONGKOS KIRIM PER MARKET ===")
print(market_shipping.sort_values('Shipping_to_Sales_%', ascending=False)[
    ['Market', 'Total_Sales', 'Total_Profit', 'Shipping_to_Sales_%', 'Profit_Margin_%']
].to_string(index=False))
print("\n")

# Interaksi Diskon Tinggi vs Ship Mode & Order Priority pada Pesanan Rugi
loss_orders = dt_store[dt_store['Profit'] < 0].copy()

ship_priority_impact = loss_orders.groupby(['Ship Mode', 'Order Priority']).agg(
    Loss_Count=('Profit', 'count'),
    Total_Loss=('Profit', 'sum'),
    Avg_Discount=('Discount', 'mean'),
    Avg_Shipping_Cost=('Shipping Cost', 'mean')
).reset_index().sort_values('Total_Loss')

print("=== KONSENTRASI RUGI BERDASARKAN SHIP MODE & ORDER PRIORITY ===")
print(ship_priority_impact.head(8).to_string(index=False))

fig, axes = plt.subplots(1, 3, figsize=(20, 5))
sns.set_theme(style="whitegrid")

# Diskon vs Profit Margin (Mencari Tipping Point)
palette_margin = ['crimson' if val < 0 else 'steelblue' for val in discount_analysis['Profit_Margin_%']]
sns.barplot(data=discount_analysis, x='Discount_Band', y='Profit_Margin_%', ax=axes[0], palette=palette_margin)
axes[0].axhline(0, color='black', linestyle='--', linewidth=0.9)
axes[0].set_title('Profit Margin by Discount Band (Tipping Point)', fontsize=12, fontweight='bold')
axes[0].set_ylabel('Profit Margin (%)')
axes[0].set_xlabel('Discount Level')

# Rasio Biaya Kirim terhadap Penjualan per Market
sns.barplot(
    data=market_shipping.sort_values('Shipping_to_Sales_%', ascending=False),
    x='Market', y='Shipping_to_Sales_%', ax=axes[1], palette='crest'
)
axes[1].set_title('Shipping Cost to Sales Ratio by Market', fontsize=12, fontweight='bold')
axes[1].set_ylabel('Shipping / Sales (%)')
axes[1].set_xlabel('Market')

# Scatter: Hubungan Diskon, Ongkir, dan Profit
sample_data = dt_store.sample(min(3000, len(dt_store)), random_state=42)
sns.scatterplot(
    data=sample_data, x='Discount', y='Profit', hue='Category',
    alpha=0.6, ax=axes[2], palette='Dark2'
)
axes[2].axhline(0, color='red', linestyle='--', linewidth=0.9)
axes[2].set_title('Discount vs Profit Distribution (Orders)', fontsize=12, fontweight='bold')
axes[2].set_xlabel('Discount Rate (0.0 - 1.0)')
axes[2].set_ylabel('Profit ($)')

plt.tight_layout()
plt.show()

